// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TurneroTcs.Data;

#nullable disable

namespace TurneroTcs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260112200318_AddVacacion")]
    partial class AddVacacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TurneroTcs.Models.Equipo", b =>
                {
                    b.Property<string>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_equipo");

                    b.HasKey("EquipoId");

                    b.ToTable("equipo");
                });

            modelBuilder.Entity("TurneroTcs.Models.Grupo", b =>
                {
                    b.Property<string>("GrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("grupo_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("ColorGrupo")
                        .HasColumnType("varchar(11)")
                        .HasColumnName("color_grupo");

                    b.Property<string>("EquipoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipo_id");

                    b.Property<string>("NombreGrupo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_grupo");

                    b.HasKey("GrupoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("EquipoId", "NombreGrupo")
                        .IsUnique();

                    b.ToTable("grupo");
                });

            modelBuilder.Entity("TurneroTcs.Models.Persona", b =>
                {
                    b.Property<string>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("EquipoId")
                        .HasColumnType("text")
                        .HasColumnName("equipo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("segundo_apellido");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("segundo_nombre");

                    b.Property<string>("Ultimatix")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("ultimatix");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("PersonaId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("persona");
                });

            modelBuilder.Entity("TurneroTcs.Models.PersonaGrupo", b =>
                {
                    b.Property<string>("PersonaGrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("persona_grupo_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<string>("GrupoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo_id");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("persona_id");

                    b.HasKey("PersonaGrupoId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("PersonaId", "GrupoId")
                        .IsUnique();

                    b.ToTable("persona_grupo");
                });

            modelBuilder.Entity("TurneroTcs.Models.RegistroTurno", b =>
                {
                    b.Property<string>("TurnoId")
                        .HasColumnType("text")
                        .HasColumnName("turno_id");

                    b.Property<DateOnly>("FechaTurno")
                        .HasColumnType("date")
                        .HasColumnName("fecha_turno");

                    b.Property<string>("GrupoId")
                        .HasColumnType("text")
                        .HasColumnName("grupo_id");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("persona_id");

                    b.Property<string>("TipoTurnoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.HasKey("TurnoId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("PersonaId", "TipoTurnoId");

                    b.ToTable("registro_turno");
                });

            modelBuilder.Entity("TurneroTcs.Models.Solicitud", b =>
                {
                    b.Property<string>("SolicitudId")
                        .HasColumnType("text")
                        .HasColumnName("solicitud_id");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("EstadoSolicitud")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado_solicitud");

                    b.Property<DateTime?>("FechaAprobacion1")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aprobacion_1");

                    b.Property<DateTime?>("FechaAprobacion2")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aprobacion_2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<string>("PersonaAprobador1Id")
                        .HasColumnType("text")
                        .HasColumnName("persona_aprobador_1_id");

                    b.Property<string>("PersonaAprobador2Id")
                        .HasColumnType("text")
                        .HasColumnName("persona_aprobador_2_id");

                    b.Property<string>("PersonaSolicitanteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("persona_solicitante_id");

                    b.Property<string>("TipoSolicitudId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_solicitud_id");

                    b.HasKey("SolicitudId");

                    b.HasIndex("EstadoSolicitud");

                    b.HasIndex("FechaSolicitud");

                    b.HasIndex("PersonaAprobador1Id");

                    b.HasIndex("PersonaAprobador2Id");

                    b.HasIndex("PersonaSolicitanteId");

                    b.HasIndex("TipoSolicitudId");

                    b.ToTable("solicitud");
                });

            modelBuilder.Entity("TurneroTcs.Models.TipoSolicitud", b =>
                {
                    b.Property<string>("TipoSolicitudId")
                        .HasColumnType("text")
                        .HasColumnName("tipo_solicitud_id");

                    b.Property<string>("NombreSolicitud")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nombre_solicitud");

                    b.HasKey("TipoSolicitudId");

                    b.ToTable("TipoSolicitudes");
                });

            modelBuilder.Entity("TurneroTcs.Models.TipoTurno", b =>
                {
                    b.Property<string>("TipoTurnoId")
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("ColorTurno")
                        .HasColumnType("varchar(11)")
                        .HasColumnName("color_turno");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("NombreTurno")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_turno");

                    b.HasKey("TipoTurnoId");

                    b.ToTable("tipo_turno");
                });

            modelBuilder.Entity("TurneroTcs.Models.Vacacion", b =>
                {
                    b.Property<string>("VacacionId")
                        .HasColumnType("text")
                        .HasColumnName("vacacion_id");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("SolicitudId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solicitud_id");

                    b.HasKey("VacacionId");

                    b.HasIndex("FechaFin");

                    b.HasIndex("FechaInicio");

                    b.HasIndex("SolicitudId");

                    b.ToTable("vacacion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TurneroTcs.Models.Grupo", b =>
                {
                    b.HasOne("TurneroTcs.Models.Equipo", "Equipo")
                        .WithMany("Grupos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TurneroTcs.Models.Persona", b =>
                {
                    b.HasOne("TurneroTcs.Models.Equipo", "Equipo")
                        .WithMany("Personas")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithOne()
                        .HasForeignKey("TurneroTcs.Models.Persona", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TurneroTcs.Models.PersonaGrupo", b =>
                {
                    b.HasOne("TurneroTcs.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("TurneroTcs.Models.RegistroTurno", b =>
                {
                    b.HasOne("TurneroTcs.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurneroTcs.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Persona");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TurneroTcs.Models.Solicitud", b =>
                {
                    b.HasOne("TurneroTcs.Models.Persona", "PersonaAprobador1")
                        .WithMany()
                        .HasForeignKey("PersonaAprobador1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurneroTcs.Models.Persona", "PersonaAprobador2")
                        .WithMany()
                        .HasForeignKey("PersonaAprobador2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurneroTcs.Models.Persona", "PersonaSolicitante")
                        .WithMany()
                        .HasForeignKey("PersonaSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.TipoSolicitud", "TipoSolicitud")
                        .WithMany()
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PersonaAprobador1");

                    b.Navigation("PersonaAprobador2");

                    b.Navigation("PersonaSolicitante");

                    b.Navigation("TipoSolicitud");
                });

            modelBuilder.Entity("TurneroTcs.Models.Vacacion", b =>
                {
                    b.HasOne("TurneroTcs.Models.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TurneroTcs.Models.Equipo", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
