// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TurneroTcs.Data;

#nullable disable

namespace TurneroTcs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526144401_AddNocturnosConsecutivos")]
    partial class AddNocturnosConsecutivos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TurneroTcs.Models.Calamidad", b =>
                {
                    b.Property<string>("CalamidadId")
                        .HasColumnType("text")
                        .HasColumnName("calamidad_id");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("varchar(240)")
                        .HasColumnName("motivo");

                    b.Property<string>("SolicitudId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solicitud_id");

                    b.HasKey("CalamidadId");

                    b.HasIndex("FechaFin");

                    b.HasIndex("FechaInicio");

                    b.HasIndex("SolicitudId")
                        .IsUnique();

                    b.ToTable("calamidad");
                });

            modelBuilder.Entity("TurneroTcs.Models.CalamidadReemplazo", b =>
                {
                    b.Property<string>("CalamidadReemplazoId")
                        .HasColumnType("text")
                        .HasColumnName("calamidad_reemplazo_id");

                    b.Property<string>("ModoReemplazo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("SWAP")
                        .HasColumnName("modo_reemplazo");

                    b.Property<string>("SolicitudId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solicitud_id");

                    b.Property<string>("TurnoAusenteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turno_ausente_id");

                    b.Property<string>("TurnoReemplazoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turno_reemplazo_id");

                    b.HasKey("CalamidadReemplazoId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("TurnoAusenteId");

                    b.HasIndex("TurnoReemplazoId");

                    b.HasIndex("SolicitudId", "TurnoAusenteId")
                        .IsUnique();

                    b.HasIndex("SolicitudId", "TurnoReemplazoId")
                        .IsUnique();

                    b.ToTable("calamidad_reemplazo");
                });

            modelBuilder.Entity("TurneroTcs.Models.CambioTurno", b =>
                {
                    b.Property<string>("CambioTurnoId")
                        .HasColumnType("text")
                        .HasColumnName("cambio_turno_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("motivo");

                    b.Property<string>("SolicitudId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solicitud_id");

                    b.Property<string>("TurnoDestinoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turno_destino_id");

                    b.Property<string>("TurnoOrigenId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turno_origen_id");

                    b.HasKey("CambioTurnoId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("TurnoDestinoId");

                    b.HasIndex("TurnoOrigenId");

                    b.ToTable("cambio_turno");
                });

            modelBuilder.Entity("TurneroTcs.Models.Equipo", b =>
                {
                    b.Property<string>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_equipo");

                    b.Property<string>("TipoGeneracion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Rotacion")
                        .HasColumnName("tipo_generacion");

                    b.HasKey("EquipoId");

                    b.ToTable("equipo");
                });

            modelBuilder.Entity("TurneroTcs.Models.EquipoPlanificacionConfig", b =>
                {
                    b.Property<string>("EquipoPlanificacionConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("equipo_planificacion_config_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<string>("EquipoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipo_id");

                    b.Property<int?>("MaximoSlotsFinSemanaPorMes")
                        .HasColumnType("integer")
                        .HasColumnName("maximo_slots_fin_semana_por_mes");

                    b.Property<int?>("MaximoTurnosNocturnosPorMes")
                        .HasColumnType("integer")
                        .HasColumnName("maximo_turnos_nocturnos_por_mes");

                    b.Property<int?>("MaximoTurnosNocturnosPorSemana")
                        .HasColumnType("integer")
                        .HasColumnName("maximo_turnos_nocturnos_por_semana");

                    b.Property<bool>("NocturnosConsecutivos")
                        .HasColumnType("boolean")
                        .HasColumnName("nocturnos_consecutivos");

                    b.HasKey("EquipoPlanificacionConfigId");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("equipo_planificacion_config");
                });

            modelBuilder.Entity("TurneroTcs.Models.EquipoTipoTurno", b =>
                {
                    b.Property<string>("EquipoId")
                        .HasColumnType("text")
                        .HasColumnName("equipo_id");

                    b.Property<string>("TipoTurnoId")
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.HasKey("EquipoId", "TipoTurnoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("TipoTurnoId");

                    b.ToTable("equipo_tipo_turno");
                });

            modelBuilder.Entity("TurneroTcs.Models.ExcepcionTurnoPersona", b =>
                {
                    b.Property<string>("ExcepcionTurnoPersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("excepcion_turno_persona_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<string>("ActualizadoPor")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("actualizado_por");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("creado_por");

                    b.Property<string>("DiasSemana")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dias_semana");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_actualizacion");

                    b.Property<string>("MotivoExcepcion")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("motivo_excepcion");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("persona_id");

                    b.Property<string>("TipoTurnoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.HasKey("ExcepcionTurnoPersonaId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("PersonaId", "FechaInicio", "FechaFin");

                    b.ToTable("excepcion_turno_persona");
                });

            modelBuilder.Entity("TurneroTcs.Models.Feriado", b =>
                {
                    b.Property<string>("FeriadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("feriado_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<DateOnly>("FinFeriado")
                        .HasColumnType("date")
                        .HasColumnName("fin_feriado");

                    b.Property<DateOnly>("InicioFeriado")
                        .HasColumnType("date")
                        .HasColumnName("inicio_feriado");

                    b.Property<string>("NombreFeriado")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombre_feriado");

                    b.HasKey("FeriadoId");

                    b.HasIndex("FinFeriado");

                    b.HasIndex("InicioFeriado");

                    b.ToTable("feriado");
                });

            modelBuilder.Entity("TurneroTcs.Models.FeriadoCoberturaConfig", b =>
                {
                    b.Property<string>("FeriadoCoberturaConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("feriado_cobertura_config_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<int>("CantidadVisible")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_visible");

                    b.Property<string>("EquipoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipo_id");

                    b.Property<string>("GrupoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo_id");

                    b.Property<string>("TipoTurnoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.HasKey("FeriadoCoberturaConfigId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("EquipoId", "GrupoId");

                    b.HasIndex("EquipoId", "GrupoId", "TipoTurnoId")
                        .IsUnique();

                    b.ToTable("feriado_cobertura_config");
                });

            modelBuilder.Entity("TurneroTcs.Models.Grupo", b =>
                {
                    b.Property<string>("GrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("grupo_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("EquipoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipo_id");

                    b.Property<string>("NombreGrupo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_grupo");

                    b.HasKey("GrupoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("EquipoId", "NombreGrupo")
                        .IsUnique();

                    b.ToTable("grupo");
                });

            modelBuilder.Entity("TurneroTcs.Models.GrupoTurnoConfig", b =>
                {
                    b.Property<string>("GrupoTurnoConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("grupo_turno_config_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dia");

                    b.Property<string>("GrupoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo_id");

                    b.Property<int>("NumeroPersonas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_personas");

                    b.Property<string>("TipoTurnoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.HasKey("GrupoTurnoConfigId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("GrupoId", "Dia", "TipoTurnoId")
                        .IsUnique();

                    b.ToTable("grupo_turno_config");
                });

            modelBuilder.Entity("TurneroTcs.Models.Permiso", b =>
                {
                    b.Property<string>("PermisoId")
                        .HasColumnType("text")
                        .HasColumnName("permiso_id");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("motivo");

                    b.Property<string>("RegistroTurnoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registro_turno_id");

                    b.Property<string>("SolicitudId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solicitud_id");

                    b.HasKey("PermisoId");

                    b.HasIndex("HoraFin");

                    b.HasIndex("HoraInicio");

                    b.HasIndex("RegistroTurnoId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("permiso");
                });

            modelBuilder.Entity("TurneroTcs.Models.PermisoAcceso", b =>
                {
                    b.Property<string>("PermisoAccesoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("permiso_acceso_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("CodigoPermiso")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("codigo_permiso");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("es_sistema");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("modulo");

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombre_permiso");

                    b.HasKey("PermisoAccesoId");

                    b.HasIndex("CodigoPermiso")
                        .IsUnique();

                    b.HasIndex("Modulo");

                    b.ToTable("permiso_acceso");
                });

            modelBuilder.Entity("TurneroTcs.Models.Persona", b =>
                {
                    b.Property<string>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<bool>("Borrado")
                        .HasColumnType("boolean")
                        .HasColumnName("borrado");

                    b.Property<DateTime?>("BorradoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("borrado_en");

                    b.Property<string>("BorradoPor")
                        .HasColumnType("text")
                        .HasColumnName("borrado_por");

                    b.Property<string>("ColorUsuario")
                        .HasColumnType("varchar(11)")
                        .HasColumnName("color_usuario");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("EquipoId")
                        .HasColumnType("text")
                        .HasColumnName("equipo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("segundo_apellido");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("segundo_nombre");

                    b.Property<string>("Ultimatix")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("ultimatix");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("PersonaId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("persona");
                });

            modelBuilder.Entity("TurneroTcs.Models.PersonaGrupo", b =>
                {
                    b.Property<string>("PersonaGrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("persona_grupo_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<bool>("EsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("es_principal");

                    b.Property<string>("GrupoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo_id");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("persona_id");

                    b.HasKey("PersonaGrupoId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("PersonaId", "GrupoId")
                        .IsUnique();

                    b.ToTable("persona_grupo");
                });

            modelBuilder.Entity("TurneroTcs.Models.Planificacion", b =>
                {
                    b.Property<string>("PlanificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("planificacion_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dia");

                    b.Property<string>("GrupoFuenteSecundariosId")
                        .HasColumnType("text")
                        .HasColumnName("grupo_fuente_secundarios_id");

                    b.Property<string>("GrupoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo_id");

                    b.Property<bool>("IsAuxiliar")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auxiliar");

                    b.Property<int>("NumeroPersonas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_personas");

                    b.Property<int>("NumeroPersonasMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("min_personas");

                    b.Property<string>("TipoTurnoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.Property<bool>("UsaSoloSecundarios")
                        .HasColumnType("boolean")
                        .HasColumnName("usa_solo_secundarios");

                    b.Property<bool>("UsarPersonaUnicaPorSemana")
                        .HasColumnType("boolean")
                        .HasColumnName("usar_persona_unica_por_semana");

                    b.HasKey("PlanificacionId");

                    b.HasIndex("GrupoFuenteSecundariosId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("GrupoId", "Dia", "TipoTurnoId", "IsAuxiliar")
                        .IsUnique();

                    b.ToTable("planificacion");
                });

            modelBuilder.Entity("TurneroTcs.Models.PlanificacionApoyoGrupo", b =>
                {
                    b.Property<string>("PlanificacionApoyoGrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("planificacion_apoyo_grupo_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<int>("CantidadApoyo")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_apoyo");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dia");

                    b.Property<string>("GrupoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo_id");

                    b.Property<string>("TipoTurnoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.HasKey("PlanificacionApoyoGrupoId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("GrupoId", "Dia", "TipoTurnoId")
                        .IsUnique();

                    b.ToTable("planificacion_apoyo_grupo");
                });

            modelBuilder.Entity("TurneroTcs.Models.PlanificacionAuxiliarEquipo", b =>
                {
                    b.Property<string>("PlanificacionAuxiliarEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("planificacion_auxiliar_equipo_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<string>("DesdeDia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desde_dia");

                    b.Property<string>("EquipoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipo_id");

                    b.Property<string>("HastaDia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hasta_dia");

                    b.Property<int>("MaxPorDia")
                        .HasColumnType("integer")
                        .HasColumnName("max_por_dia");

                    b.Property<string>("TipoTurnoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.HasKey("PlanificacionAuxiliarEquipoId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("EquipoId", "TipoTurnoId")
                        .IsUnique();

                    b.ToTable("planificacion_auxiliar_equipo");
                });

            modelBuilder.Entity("TurneroTcs.Models.PlanificacionAuxiliarEquipoGrupo", b =>
                {
                    b.Property<string>("PlanificacionAuxiliarEquipoGrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("planificacion_auxiliar_equipo_grupo_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<string>("GrupoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo_id");

                    b.Property<string>("PlanificacionAuxiliarEquipoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("planificacion_auxiliar_equipo_id");

                    b.HasKey("PlanificacionAuxiliarEquipoGrupoId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("PlanificacionAuxiliarEquipoId", "GrupoId")
                        .IsUnique();

                    b.ToTable("planificacion_auxiliar_equipo_grupo");
                });

            modelBuilder.Entity("TurneroTcs.Models.PlanificacionBlueprint", b =>
                {
                    b.Property<string>("PlanificacionBlueprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("planificacion_blueprint_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("dia");

                    b.Property<string>("Etiquetas")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("etiquetas");

                    b.Property<string>("GrupoId")
                        .HasColumnType("text")
                        .HasColumnName("grupo_id");

                    b.Property<int>("MinPersonasTurno")
                        .HasColumnType("integer")
                        .HasColumnName("min_personas_turno");

                    b.Property<string>("TipoTurnoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.Property<bool>("UsaGruposSecundarios")
                        .HasColumnType("boolean")
                        .HasColumnName("usa_grupos_secundarios");

                    b.HasKey("PlanificacionBlueprintId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("GrupoId", "Dia", "TipoTurnoId")
                        .IsUnique();

                    b.ToTable("planificacion_blueprint");
                });

            modelBuilder.Entity("TurneroTcs.Models.PlanificacionTurnoOpcionalVacacionGrupo", b =>
                {
                    b.Property<string>("PlanificacionTurnoOpcionalVacacionGrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("planificacion_turno_opcional_vacacion_grupo_id")
                        .HasDefaultValueSql("generate_short_id()");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dia");

                    b.Property<string>("GrupoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo_id");

                    b.Property<string>("TipoTurnoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.HasKey("PlanificacionTurnoOpcionalVacacionGrupoId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("GrupoId", "Dia", "TipoTurnoId")
                        .IsUnique();

                    b.ToTable("planificacion_turno_opcional_vacacion_grupo");
                });

            modelBuilder.Entity("TurneroTcs.Models.RegistroTurno", b =>
                {
                    b.Property<string>("TurnoId")
                        .HasColumnType("text")
                        .HasColumnName("turno_id");

                    b.Property<bool>("EsFeriado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_feriado");

                    b.Property<bool>("EsTurnoExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_turno_extra");

                    b.Property<DateOnly>("FechaTurno")
                        .HasColumnType("date")
                        .HasColumnName("fecha_turno");

                    b.Property<string>("GrupoId")
                        .HasColumnType("text")
                        .HasColumnName("grupo_id");

                    b.Property<bool>("NoLaboradoPorFeriado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("no_laborado_por_feriado");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("persona_id");

                    b.Property<string>("TipoTurnoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.HasKey("TurnoId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("PersonaId", "TipoTurnoId");

                    b.HasIndex("FechaTurno", "EsFeriado", "NoLaboradoPorFeriado");

                    b.HasIndex("PersonaId", "FechaTurno", "EsTurnoExtra");

                    b.ToTable("registro_turno");
                });

            modelBuilder.Entity("TurneroTcs.Models.RolPermisoAcceso", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.Property<string>("PermisoAccesoId")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("permiso_acceso_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.HasKey("RoleId", "PermisoAccesoId");

                    b.HasIndex("PermisoAccesoId");

                    b.ToTable("rol_permiso_acceso");
                });

            modelBuilder.Entity("TurneroTcs.Models.Solicitud", b =>
                {
                    b.Property<string>("SolicitudId")
                        .HasColumnType("text")
                        .HasColumnName("solicitud_id");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("EstadoSolicitud")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado_solicitud");

                    b.Property<DateTime?>("FechaAprobacion1")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aprobacion_1");

                    b.Property<DateTime?>("FechaAprobacion2")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aprobacion_2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<string>("PersonaAprobador1Id")
                        .HasColumnType("text")
                        .HasColumnName("persona_aprobador_1_id");

                    b.Property<string>("PersonaAprobador2Id")
                        .HasColumnType("text")
                        .HasColumnName("persona_aprobador_2_id");

                    b.Property<string>("PersonaSolicitanteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("persona_solicitante_id");

                    b.Property<string>("TipoSolicitudId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_solicitud_id");

                    b.HasKey("SolicitudId");

                    b.HasIndex("EstadoSolicitud");

                    b.HasIndex("FechaSolicitud");

                    b.HasIndex("PersonaAprobador1Id");

                    b.HasIndex("PersonaAprobador2Id");

                    b.HasIndex("PersonaSolicitanteId");

                    b.HasIndex("TipoSolicitudId");

                    b.ToTable("solicitud");
                });

            modelBuilder.Entity("TurneroTcs.Models.TipoSolicitud", b =>
                {
                    b.Property<string>("TipoSolicitudId")
                        .HasColumnType("text")
                        .HasColumnName("tipo_solicitud_id");

                    b.Property<string>("NombreSolicitud")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nombre_solicitud");

                    b.HasKey("TipoSolicitudId");

                    b.ToTable("TipoSolicitudes");
                });

            modelBuilder.Entity("TurneroTcs.Models.TipoTurno", b =>
                {
                    b.Property<string>("TipoTurnoId")
                        .HasColumnType("text")
                        .HasColumnName("tipo_turno_id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("NombreTurno")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_turno");

                    b.HasKey("TipoTurnoId");

                    b.ToTable("tipo_turno");
                });

            modelBuilder.Entity("TurneroTcs.Models.UsuarioPermisoAcceso", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("PermisoAccesoId")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("permiso_acceso_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<bool>("EsDenegado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_denegado");

                    b.HasKey("UserId", "PermisoAccesoId");

                    b.HasIndex("PermisoAccesoId");

                    b.HasIndex("UserId", "EsDenegado");

                    b.ToTable("usuario_permiso_acceso");
                });

            modelBuilder.Entity("TurneroTcs.Models.Vacacion", b =>
                {
                    b.Property<string>("VacacionId")
                        .HasColumnType("text")
                        .HasColumnName("vacacion_id");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("SolicitudId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solicitud_id");

                    b.HasKey("VacacionId");

                    b.HasIndex("FechaFin");

                    b.HasIndex("FechaInicio");

                    b.HasIndex("SolicitudId");

                    b.ToTable("vacacion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TurneroTcs.Models.Calamidad", b =>
                {
                    b.HasOne("TurneroTcs.Models.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TurneroTcs.Models.CalamidadReemplazo", b =>
                {
                    b.HasOne("TurneroTcs.Models.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.RegistroTurno", "TurnoAusente")
                        .WithMany()
                        .HasForeignKey("TurnoAusenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.RegistroTurno", "TurnoReemplazo")
                        .WithMany()
                        .HasForeignKey("TurnoReemplazoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("TurnoAusente");

                    b.Navigation("TurnoReemplazo");
                });

            modelBuilder.Entity("TurneroTcs.Models.CambioTurno", b =>
                {
                    b.HasOne("TurneroTcs.Models.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.RegistroTurno", "TurnoDestino")
                        .WithMany()
                        .HasForeignKey("TurnoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.RegistroTurno", "TurnoOrigen")
                        .WithMany()
                        .HasForeignKey("TurnoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("TurnoDestino");

                    b.Navigation("TurnoOrigen");
                });

            modelBuilder.Entity("TurneroTcs.Models.EquipoPlanificacionConfig", b =>
                {
                    b.HasOne("TurneroTcs.Models.Equipo", "Equipo")
                        .WithMany("PlanificacionConfigs")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TurneroTcs.Models.EquipoTipoTurno", b =>
                {
                    b.HasOne("TurneroTcs.Models.Equipo", "Equipo")
                        .WithMany("EquipoTipoTurnos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.TipoTurno", "TipoTurno")
                        .WithMany("EquipoTipoTurnos")
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TurneroTcs.Models.ExcepcionTurnoPersona", b =>
                {
                    b.HasOne("TurneroTcs.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TurneroTcs.Models.FeriadoCoberturaConfig", b =>
                {
                    b.HasOne("TurneroTcs.Models.Equipo", "Equipo")
                        .WithMany("FeriadoCoberturaConfigs")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Grupo");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TurneroTcs.Models.Grupo", b =>
                {
                    b.HasOne("TurneroTcs.Models.Equipo", "Equipo")
                        .WithMany("Grupos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TurneroTcs.Models.GrupoTurnoConfig", b =>
                {
                    b.HasOne("TurneroTcs.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TurneroTcs.Models.Permiso", b =>
                {
                    b.HasOne("TurneroTcs.Models.RegistroTurno", "RegistroTurno")
                        .WithMany()
                        .HasForeignKey("RegistroTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegistroTurno");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TurneroTcs.Models.Persona", b =>
                {
                    b.HasOne("TurneroTcs.Models.Equipo", "Equipo")
                        .WithMany("Personas")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithOne()
                        .HasForeignKey("TurneroTcs.Models.Persona", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TurneroTcs.Models.PersonaGrupo", b =>
                {
                    b.HasOne("TurneroTcs.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("TurneroTcs.Models.Planificacion", b =>
                {
                    b.HasOne("TurneroTcs.Models.Grupo", "GrupoFuenteSecundarios")
                        .WithMany()
                        .HasForeignKey("GrupoFuenteSecundariosId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurneroTcs.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("GrupoFuenteSecundarios");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TurneroTcs.Models.PlanificacionApoyoGrupo", b =>
                {
                    b.HasOne("TurneroTcs.Models.Grupo", "Grupo")
                        .WithMany("PlanificacionesApoyo")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TurneroTcs.Models.PlanificacionAuxiliarEquipo", b =>
                {
                    b.HasOne("TurneroTcs.Models.Equipo", "Equipo")
                        .WithMany("PlanificacionesAuxiliaresEquipo")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TurneroTcs.Models.PlanificacionAuxiliarEquipoGrupo", b =>
                {
                    b.HasOne("TurneroTcs.Models.Grupo", "Grupo")
                        .WithMany("PlanificacionesAuxiliaresEquipo")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.PlanificacionAuxiliarEquipo", "PlanificacionAuxiliarEquipo")
                        .WithMany("GruposPermitidos")
                        .HasForeignKey("PlanificacionAuxiliarEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("PlanificacionAuxiliarEquipo");
                });

            modelBuilder.Entity("TurneroTcs.Models.PlanificacionBlueprint", b =>
                {
                    b.HasOne("TurneroTcs.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurneroTcs.Models.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TurneroTcs.Models.PlanificacionTurnoOpcionalVacacionGrupo", b =>
                {
                    b.HasOne("TurneroTcs.Models.Grupo", "Grupo")
                        .WithMany("PlanificacionesTurnosOpcionalesVacacion")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TurneroTcs.Models.RegistroTurno", b =>
                {
                    b.HasOne("TurneroTcs.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurneroTcs.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Persona");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TurneroTcs.Models.RolPermisoAcceso", b =>
                {
                    b.HasOne("TurneroTcs.Models.PermisoAcceso", "PermisoAcceso")
                        .WithMany("RolesAsignados")
                        .HasForeignKey("PermisoAccesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermisoAcceso");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TurneroTcs.Models.Solicitud", b =>
                {
                    b.HasOne("TurneroTcs.Models.Persona", "PersonaAprobador1")
                        .WithMany()
                        .HasForeignKey("PersonaAprobador1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurneroTcs.Models.Persona", "PersonaAprobador2")
                        .WithMany()
                        .HasForeignKey("PersonaAprobador2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurneroTcs.Models.Persona", "PersonaSolicitante")
                        .WithMany()
                        .HasForeignKey("PersonaSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurneroTcs.Models.TipoSolicitud", "TipoSolicitud")
                        .WithMany()
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PersonaAprobador1");

                    b.Navigation("PersonaAprobador2");

                    b.Navigation("PersonaSolicitante");

                    b.Navigation("TipoSolicitud");
                });

            modelBuilder.Entity("TurneroTcs.Models.UsuarioPermisoAcceso", b =>
                {
                    b.HasOne("TurneroTcs.Models.PermisoAcceso", "PermisoAcceso")
                        .WithMany("UsuariosAsignados")
                        .HasForeignKey("PermisoAccesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermisoAcceso");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TurneroTcs.Models.Vacacion", b =>
                {
                    b.HasOne("TurneroTcs.Models.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TurneroTcs.Models.Equipo", b =>
                {
                    b.Navigation("EquipoTipoTurnos");

                    b.Navigation("FeriadoCoberturaConfigs");

                    b.Navigation("Grupos");

                    b.Navigation("Personas");

                    b.Navigation("PlanificacionConfigs");

                    b.Navigation("PlanificacionesAuxiliaresEquipo");
                });

            modelBuilder.Entity("TurneroTcs.Models.Grupo", b =>
                {
                    b.Navigation("PlanificacionesApoyo");

                    b.Navigation("PlanificacionesAuxiliaresEquipo");

                    b.Navigation("PlanificacionesTurnosOpcionalesVacacion");
                });

            modelBuilder.Entity("TurneroTcs.Models.PermisoAcceso", b =>
                {
                    b.Navigation("RolesAsignados");

                    b.Navigation("UsuariosAsignados");
                });

            modelBuilder.Entity("TurneroTcs.Models.PlanificacionAuxiliarEquipo", b =>
                {
                    b.Navigation("GruposPermitidos");
                });

            modelBuilder.Entity("TurneroTcs.Models.TipoTurno", b =>
                {
                    b.Navigation("EquipoTipoTurnos");
                });
#pragma warning restore 612, 618
        }
    }
}
